### PR TITLE
Update to pom-scijava 29 API

### PR DESCRIPTION
**Pull request by hinerm**
Closes https://github.com/scijava/pom-scijava/issues/122

Related issues and forum threads:
* https://github.com/scijava/pom-scijava/issues/173
* https://github.com/scijava/pom-scijava/issues/122
* [Updating ImageJ-OMERO for OMERO 5.5 and 5.6](https://forum.image.sc/t/34044)
* [Imagej-omero isn’t working with scifio 0.41.0](https://forum.image.sc/t/44111)
* [ImageJ-OMERO plugin not connecting to demo.openmicroscopy site](https://forum.image.sc/t/64693)
* [OMERO Connection in KNIME does not work](https://forum.image.sc/t/31489)
* [Omero FIJI plugin not working on server v5.6](https://forum.image.sc/t/37493)
* [Best way imageJ to open an ImagePlus from OMERO using Bioformats](https://forum.image.sc/t/26651)
* [Omero Tips January edition : Fiji Omero plugin (1/3) - Installation](https://forum.image.sc/t/48125)

### CODE REVIEW

**Comment by ctrueden** [comment]
@joshmoore Could I ask for your help in getting the Travis build integration test passing again? I'd like to validate and release the latest imagej-omero (built on the new SCIFIO API, and which should support OMERO 5.5/5.6 now).

We discontinued test.imagej.net, so I relocated the omero_test_infra_backup.zip to https://downloads.imagej.net/test/omero/. That part works fine, but the Docker setup fails soon after with:
```
Creating imagejomero_db_1_8ebb8ec7001a ... 
Creating imagejomero_web_1_efce88973816 ... 
Creating imagejomero_omero_1_4f432b9fea8f ... 
Error: No such container:path: imagejomero_omero_1:/
```

Any ideas?

I also noticed that `.travis/test.sh` still references OMERO 5.4... should this be changed to 5.5 or 5.6? Any other needed changes to that script or elsewhere?

Thanks a lot for your help!

**Comment by joshmoore** [comment]
The issue with the 5.4 versions seems to be the Python 2 --> 3 upgrade:

```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/opt/omero/server/venv3/bin/python\": stat /opt/omero/server/venv3/bin/python: no such file or directory": unknown
```

Assuming there's not much value in investing in OMERO 5.4, I haven't looked into a workaround.

Bumping to 5.6, it looks like the primary issue is the bump of the default PostgreSQL version. The stored backup uses 9.6 and would need upgrading. An easier workaround is to pin to 9.6:

```
(base) ~/opt/imagej-omero $git diff
diff --git a/.travis/test.sh b/.travis/test.sh
index 9e09f63..68df1fd 100755
--- a/.travis/test.sh
+++ b/.travis/test.sh
@@ -24,8 +24,10 @@ fi

 # TODO: remove SSLUtils when bumping to 5.5
 # see: https://github.com/imagej/imagej-omero/pull/105
-export OMERO_SERVER_VERSION=5.4
-export OMERO_WEB_VERSION=5.4
+export OMERO_SERVER_VERSION=5.6
+export OMERO_WEB_VERSION=5.6
+export POSTGRES_VERSION=9.6
+
 export COMPOSE_FILE="docker-compose.yml:volumes.yml"

 .omero/docker lib
```

However, even with this there's a failure:

```
Jun 07, 2020 10:05:25 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
[ERROR] Tests run: 11, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 5.993 s <<< FAILURE! - in net.imagej.omero.it.OmeroIT
[ERROR] testDownloadThenUploadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.101 s  <<< ERROR!
java.io.IOException: Unresolvable source: omero:server=omero&port=4064&sessionID=639c1b4b-2536-4dd8-94b8-c6a2e67e3127&imageID=1
	at net.imagej.omero.it.OmeroIT.testDownloadThenUploadImage(OmeroIT.java:157)

[ERROR] testUploadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.027 s  <<< ERROR!
java.io.IOException: Unresolvable source: http://imagej.net/images/blobs.gif
	at net.imagej.omero.it.OmeroIT.testUploadImage(OmeroIT.java:141)

[ERROR] testDownloadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.075 s  <<< ERROR!
java.io.IOException: Unresolvable source: omero:server=omero&port=4064&sessionID=3e1a96b9-d83f-4500-b8ce-95ff5eef9ac2&imageID=1
	at net.imagej.omero.it.OmeroIT.testDownloadImage(OmeroIT.java:130)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   OmeroIT.testDownloadImage:130 » IO Unresolvable source: omero:server=omero&por...
[ERROR]   OmeroIT.testDownloadThenUploadImage:157 » IO Unresolvable source: omero:server...
[ERROR]   OmeroIT.testUploadImage:141 » IO Unresolvable source: http://imagej.net/images...
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 3, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default-cli) @ imagej-omero ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.731 s
[INFO] Finished at: 2020-06-07T10:05:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default-cli) on project imagej-omero: There are test failures.
[ERROR]
[ERROR] Please refer to /src/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Could this be related to the new `Location` logic, or do I need to dig deeper? The server _appears_ to be up and running:

```
(base) ~/opt/imagej-omero $.omero/compose exec omero bash
bash-4.2$ /opt/omero/server/venv3/bin/omero login root@localhost
Password:
Created session for root@localhost:4064. Idle timeout: 10 min. Current group: system
bash-4.2$ /opt/omero/server/venv3/bin/omero hql "from Image"
Using session for root@localhost:4064. Idle timeout: 10 min. Current group: system
 # | Class  | Id | details         | series | fileset    | name                                         | version | description
---+--------+----+-----------------+--------+------------+----------------------------------------------+---------+------------------------------------
 0 | ImageI | 1  | owner=0;group=0 | 0      | FilesetI:1 | test&rectangle=10&ellipsis=10&points=10.fake |         |
 1 | ImageI | 2  | owner=0;group=0 | 0      |            | http://imagej.net/images/blobs.gif           | 0       | http://imagej.net/images/blobs.gif
(2 rows)
```

**Comment by ctrueden** [comment]
@joshmoore Thanks a lot! I think we need a new `LocationResolver` plugin for OMERO locations. I am happy to work on it, now that you solve the infrastructural issues. Can you file a PR fixing the Docker- and version-related stuff, but which still has the test failures? As long as I can reproduce, I'm happy to work on fixing it.

**Comment by joshmoore** [comment]
> Is anything else necessary?

I don't think so. `env NOCLEAN=true .travis/test.sh` will leave the docker containers around so that you can inspect what's happening.

**Comment by ctrueden** [comment]
Status update: I've not had initial success on the Docker front:
```
Successfully built 9a2aa1f56e26
Successfully tagged test:latest
Traceback (most recent call last):
  File "/infra/wait-on-login", line 4, in <module>
    import omero
ImportError: No module named omero
```
So clearly something is not quite right there.

Rather than troubleshooting that, I thought I'd do a review of the code, knowing that we at least need a new `OMEROLocationResolver` plugin, and probably other changes. And indeed, there are several parts of the code that could and should now be updated to reflect the new possibilities and requirements of the SciJava `Location` API.

So I'm going to dive in with that first, and only after I'm satisfied that the codebase is in good shape try again with the docker-based integration test. @joshmoore If you immediately know how to deal with (or start troubleshooting) the error above, I'd appreciate pointers, but it's not super urgent, since I'll be working on the Java codebase first.

**Comment by joshmoore** [comment]
@ctrueden : odd! I can't reproduce. From your last commit, I get this:

<details><summary>docker log</summary>

```
Successfully built b4e894c62cd1
Successfully tagged test:latest
travis_fold:start:wait-on-login
Sleeping for 30
travis_fold:end:wait-on-login
No script found:
  .omeroci/test-data
  .omero/test-data
  .omero/lib-data
ignore
mkdir: can't create directory '/root/.m2/': Permission denied
Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions? Carrying on ...
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< net.imagej:imagej-omero >-----------------------
[INFO] Building ImageJ-OMERO interoperability 1.0.0-5.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default-cli) @ imagej-omero ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.22.2/surefire-junit4-2.22.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.22.2/surefire-junit4-2.22.2.pom (3.1 kB at 3.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.22.2/surefire-providers-2.22.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.22.2/surefire-providers-2.22.2.pom (2.5 kB at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.22.2/surefire-junit4-2.22.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.22.2/surefire-junit4-2.22.2.jar (85 kB at 137 kB/s)
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.imagej.omero.it.OmeroIT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ECLIPSE HELPER] Indexing annotations...
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Jun 15, 2020 7:33:30 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
[ERROR] Tests run: 11, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 3.729 s <<< FAILURE! - in net.imagej.omero.it.OmeroIT
[ERROR] testDownloadThenUploadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.081 s  <<< ERROR!
java.io.IOException: Unresolvable source: omero:server=omero&port=4064&sessionID=4dd587b9-9c40-495d-b397-9dd76e8d140a&imageID=1
	at net.imagej.omero.it.OmeroIT.testDownloadThenUploadImage(OmeroIT.java:157)

[ERROR] testUploadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.039 s  <<< ERROR!
java.io.IOException: Unresolvable source: http://imagej.net/images/blobs.gif
	at net.imagej.omero.it.OmeroIT.testUploadImage(OmeroIT.java:141)

[ERROR] testDownloadImage(net.imagej.omero.it.OmeroIT)  Time elapsed: 0.049 s  <<< ERROR!
java.io.IOException: Unresolvable source: omero:server=omero&port=4064&sessionID=a459961a-27ec-495b-9b53-3f93bc1bdb59&imageID=1
	at net.imagej.omero.it.OmeroIT.testDownloadImage(OmeroIT.java:130)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   OmeroIT.testDownloadImage:130 » IO Unresolvable source: omero:server=omero&por...
[ERROR]   OmeroIT.testDownloadThenUploadImage:157 » IO Unresolvable source: omero:server...
[ERROR]   OmeroIT.testUploadImage:141 » IO Unresolvable source: http://imagej.net/images...
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 3, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default-cli) @ imagej-omero ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.708 s
[INFO] Finished at: 2020-06-15T19:33:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default-cli) on project imagej-omero: There are test failures.
[ERROR]
[ERROR] Please refer to /src/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

</details>

I assume all the standards of no local diff, pulled recent versions of the images, etc. hold. Are you running this on Docker Desktop? Happy to wait until you have a next commit if it doesn't go green. Sorry for the troubles.

**Comment by joshmoore** [comment]
Looks like tests are running again:

```
2509[INFO] -------------------------------------------------------------
2510[ERROR] COMPILATION ERROR : 
2511[INFO] -------------------------------------------------------------
2512[ERROR] /src/src/main/java/net/imagej/omero/OMEROLocationResolver.java:[56,37] ')' expected
2513[ERROR] /src/src/main/java/net/imagej/omero/OMEROLocationResolver.java:[56,44] illegal start of expression
2514[ERROR] /src/src/main/java/net/imagej/omero/DefaultOMEROService.java:[526,75] ';' expected
2515[INFO] 3 errors 
```

Sorry. No idea what the cause was, but bumping the test-infra version seems to have helped.

**Comment by ctrueden** [comment]
Thanks @joshmoore for the followup! I'll be on vacation from tomorrow through October 4, but plan to work on completing this soon after I return.

**Comment by ctrueden** [comment]
Today, @nicost and I worked on this, and pushed some more progress to a new branch called `omero-5.6`. I will keep working on it, and update this PR accordingly once ready.

**Pull request closed without merging**
